### PR TITLE
PHP 8.2 Update

### PR DESCRIPTION
**Pull request by CallMeJon90**

### CODE REVIEW

**Comment by faizanakram99** [comment]
@ifsnop can we please get this merged, i know you don't often make contributions to this repository but this small fix will make this lib compatible with PHP 8.2.

**Comment by smalos** [comment]
I think the [druidfi](https://github.com/druidfi/mysqldump-php) fork should be used since it's 119 commits ahead of ifsnop.

**Comment by garas** [comment]
@ifsnop If you have no plans to maintain this package anymore, you should mark it as _abandoned_ so everybody would know that so they could search for replacement.

Go to [packagist.org](https://packagist.org/packages/ifsnop/mysqldump-php), login and click the button "Abandon". There you can also enter `druidfi/mysqldump-php` as suggested replacement. Also update Readme.

**Comment by ifsnop** [comment]
No intention on abandoning this project, but real life problems keep me busy. I have added this commit, since it is backwards compatible and it needed to be done several years ago.

**Pull request merged**
