### PR TITLE
adding support for insert ignore

### PR DESCRIPTION
**Pull request by matthiaz**
It seemed to be missing, don't know why really... So I added it.
https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_insert-ignore

### CODE REVIEW

**Comment by ifsnop** [comment]
Seems that some tests fails. Would you mind adding/fixing the tests and update the README file?

Thanks a lot!

**Comment by matthiaz** [comment]
Ok, it took me a while to figure out how the tests work. But I think I got it straightened out.

**Comment by matthiaz** [comment]
Euhm... hhvm build is giving a segfault, any idea why? Can I force travis to retry? Might be a temporary issue?

**Comment by ifsnop** [comment]
Travis-ci trusty image has been updated, so maybe something is broken. Only test that fails is the hhvm build, and fails when executing the test.php file, that shouldn't fail.

I have changed some options from the travis.yml file, as per https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch, if it doesn't work I will disable hhvm tests for a while.

**Comment by matthiaz** [comment]
Better disable HHVM, it still segfaults....

**Comment by ifsnop** [comment]
I'm very sorry, but when I merged the skip-definer patch, some things changed, because new tests where added. Since having a INSERT IGNORE switch is a useful thing, could you please update your patch so I can merge it?

Thanks in advance!

**Comment by aripringle** [comment]
Hi, any chance that this might get fixed & merged in? I could really use this feature.

Otherwise I'll see if I can make a new PR with similar changes.

**Comment by ifsnop** [comment]
If you prepare a PR, I will merge it ASAP.

Thanks in advance!

**Comment by ifsnop** [comment]
Added in #143

**Pull request closed without merging**
