### PR TITLE
CompressNone performance improvements

### PR DESCRIPTION
**Pull request by roeycohen**
add buffering to CompressNone as it works much faster

### CODE REVIEW

**Comment by roeycohen** [comment]
this relates to PR #280 but takes a different approach.

p.s. 
tiny writes don't seem to affect zip streams performance - it probably already have some kind of buffering.

**Comment by roeycohen** [comment]
hi @ifsnop, do you need me to make more adjustments to confirm this PR?

**Comment by ifsnop** [comment]
Just give me some a couple of days, testing machine break and i would like to make some more tests.

**Comment by ifsnop** [comment]
I think I prefer #280 over #284, since less calls to compressManager looks better to me.

**Pull request closed without merging**
