### PR TITLE
Improve the library extensibility

### PR DESCRIPTION
**Pull request by KamilBaczkowski**
The library is great and works well, unfortunately it doesn't give much to work with when it comes to changing or extending the current behaviour.
One of the examples is the variable `$dumpSettingsDefault` from the `__construct` method in the `Mysqldump` class; it actively blocks extensibility, by throwing an error when any non-Mysqldump-standard arguments were passed. I moved it to the class scope, and because of it, anyone wanting to extend the library with new args can just add their own arguments to that array, thus providing a safe to use interface that fails on unknown arguments, but is also extensible.
In my own case, I wanted to disable dumping of the views. Unfortunately, since all the methods are protected, I couldn't achieve that (I wanted to specifically reduce the number of queries send to `INFORMATION_SCHEMA`).

I hope some meaningful discussion emerges and eventually this PR will be merged.

### CODE REVIEW

**Comment by ifsnop** [comment]
Looks like the build failed because of travis, I'm restarting the check.

Meanwhile, for me its ok to change the visibility, after @KamilBaczkowski and what was said by @luc45 in #200.

Same comment here as in the patch to reuse a pdo connection. User can break things and blame mysqldump-php. But if user is extending this library, [s]he is advanced enough to fix his/her own problems.

Will this patch solve both (#200 & #202) issues? @KamilBaczkowski , anything you want to add?

**Comment by KamilBaczkowski** [comment]
For it to also fix #200 it would have to move PDO default settings to the class instead of limiting it to the constructor. I can do that easily in this PR too.

**Comment by krowinski** [comment]
any update when this will be merged ?

**Comment by ifsnop** [comment]
Merged.

**Pull request closed without merging**
