### PR TITLE
Ability to append instead of overwriting dumps

### PR DESCRIPTION
**Pull request by jmserra**
New dump function '->append($filename)'

### CODE REVIEW

**Comment by ifsnop** [comment]
Maybe it is easier to just keep the open function, and pass the open mode in the parameters array. By default, it could be "wb", but could be overwritten with "a" ?

**Comment by jmserra** [comment]
Im not sure about that, because i think its more flexible if we give such option through the functions, in that case you would be able to call for example ->start() and then ->append() to diferent files, being able to dump twice the same contents in different ways in different files without needing to reset the object or the settings
But its almost the same :)

**Comment by ifsnop** [comment]
Nothing is kept in memory during a dump, so there is no improvement from calling start() and the append(). Also, locks aren't held between two calls (so database isn't blocked), and table structure could be changed. 

To ensure a correct dump, everything should be repeated by calling start() again.

**Comment by ifsnop** [comment]
If you add to the constructor a new option to define between "overwrite" or "append", and then call the open function with the right parameters, I will merge it ASAP.

**Pull request closed without merging**
