### PR TITLE
Optional parameter to getFilename to guess the archive filename that will be created

### PR DESCRIPTION
**Pull request by gwarnants**
This modification allows getFilename() to be called before the start() method. This can be useful to control if the dump has already been written, and don't overwrite it (ie: in case of a daily dump that should be done only once)

```php
$settings = array(
    'compress' => Mysqldump::GZIP
);

$output = 'dump.sql';
$dump = new Mysqldump($db, $username, $password, $host, $type, $settings);
if (!is_file($dump->getFilename($output)) { // test if dump.sql.gz already exists, to don't write it twice
    $dump->start($output); // write dump.sql.gz
}
```

### CODE REVIEW

**Comment by ifsnop** [comment]
Isn't easier to refuse overwriting the file during dump and raise and
exception that can be catched by the caller? What do you think?

**Comment by gwarnants** [comment]
Yes, but sometimes I think it could be useful to overwrite the dump. If the class always refuse overwriting from CompressManager::open(), we then will need to provide a new constructor setting, ie "allow_overwrite".

Please also consider this problem is related to my last issue (https://github.com/ifsnop/mysqldump-php/issues/75)

**Comment by ifsnop** [comment]
I believe that if extension appending is removed, there should be no need to query for the output filename.

**Comment by ifsnop** [comment]
As per scrutinizer-ci: The property archiveFilename does not exist. Did you maybe forget to declare it? 
Could you fix it?

**Comment by gwarnants** [comment]
Sorry. Now fixed

**Pull request merged**
