### PR TITLE
Add opportunity to use external database handler

### PR DESCRIPTION
**Pull request by DmitryKrekota**
I have existing PDO database handler from my framework. I want to use it without creating new connection.  This PR will help to do this.

### CODE REVIEW

**Comment by ifsnop** [comment]
When using an external database handler, code has to make some cleanup that I'm not sure it can be done once the connection has been made. For example:
~~~
$pdo->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, false);
~~~
is needed to dump large databases without running out of memory in the php process.

Is there any benefit from using a previously opened database handler?

**Comment by DmitryKrekota** [comment]
For me it is more convenient when my database settings are located in one place. Also, default library settings converts russian symbols in ????? symbols for my database and I do not know how to solve the problem in another way.

**Comment by ifsnop** [comment]
Could you provide a small working dump (with mysqldump or mysqldump-php) so
I could have a look into it?

Definitely that should never happen!

--
-- Madrid / Spain

**Comment by DmitryKrekota** [comment]
Sorry for the long answer, but I did not have a free time for the PR. Olso, I do not have SQL dump for now. The PR is no actual for me now, so I close it.

**Pull request closed without merging**
